# Tips

# Always check the Continue on error option of secure development build tasks.
# To run analysis after your build, keep the secure development build tasks after the publish build artifacts step of your build. So, your build can finish and post results before running analysis.
# Secure Development build tasks will fail if the tool fails to complete successfully but will NOT fail if/when the tool completes successfully and identifies issues in the code.
# You can configure your build to break when a tool identifies issues in the code; see Post Analysis below.
# One exception is the Antimalware task, which will fail if the tool completes and finds malware.

trigger: none

pool:
  name: MyLenovoP1

steps:
# ---------------------------------  Build

# ---------------------------------  Publish build artifact(s)

# ---------------------------------  Analysis 

- task: Armory@2
  continueOnError: true
  inputs:
    targetDirectory: '$(Build.SourcesDirectory)'
    targetFiles: 'f|**\*.json;-|.gdn\**;'

# ---------------------------------  Publishing MSCA reports/logs
- task: SdtReport@1
  continueOnError: true
  inputs:
    AllTools: true
    BinSkimBreakOn: 'WarningAbove'
    CodesignValidationBreakOn: 'WarningAbove'
    FxCopBreakOn: 'ErrorAbove'
    ModernCopBreakOn: 'WarningAbove'
    PoliCheckBreakOn: 'Severity4Above'
    RoslynAnalyzersBreakOn: 'WarningAbove'
    SemmleBreakOn: 'WarningAbove'
    TSLintBreakOn: 'WarningAbove'
    ToolLogsNotFoundAction: 'Standard'

- task: PublishSecurityAnalysisLogs@2
  inputs:
    ArtifactName: 'CodeAnalysisLogs'
    ArtifactType: 'FilePath'
    TargetPath: 'c:\temp\'
    AllTools: true
    ToolLogsNotFoundAction: 'Standard'