pool:
  vmImage: 'ubuntu-latest'

container: ubuntu:18.04

steps:

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: 'gitversion.yml'