pool:
  vmImage: 'ubuntu-latest'

container: ubuntu:18.04

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: 'GitVersion.yml'